import {
    AppBar, Avatar, Backdrop, Badge, BottomNavigation, BottomNavigationAction, Button, ButtonBase, Card, CardActionArea, CardActions, CardContent, CardHeader,
    CardMedia, Checkbox, Chip, CircularProgress, ClickAwayListener, Collapse, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Divider,
    Drawer, ExpansionPanel, ExpansionPanelActions, ExpansionPanelDetails, ExpansionPanelSummary, Fab, Fade, FilledInput, FormControl, FormControlLabel,
    FormGroup, FormHelperText, FormLabel, Grid, GridList, GridListTile, GridListTileBar, Grow, Hidden, Icon, IconButton, Input, InputAdornment, InputBase,
    InputLabel, LinearProgress, Link, List, ListItem, ListItemAvatar, ListItemIcon, ListItemSecondaryAction, ListItemText, ListSubheader, Menu, MenuItem,
    MenuList, MobileStepper, Modal, MuiThemeProvider, NativeSelect, OutlinedInput, Paper, Popover, Popper, Portal, Radio, RadioGroup, Select, Slide, Snackbar,
    SnackbarContent, Step, StepButton, StepConnector, StepContent, StepIcon, StepLabel, Stepper, SvgIcon, SwipeableDrawer, Switch, Tab, Table, TableBody, TableCell,
    TableFooter, TableHead, TablePagination, TableRow, TableSortLabel, Tabs, TextField, Toolbar, Tooltip, Typography, Zoom
} from '@material-ui/core';
import TouchRipple from '@material-ui/core/ButtonBase/TouchRipple';

// Action icons
import {
    ThreeDRotation, Accessibility, AccessibilityNew, Accessible, AccessibleForward, AccountBalance, AccountBalanceWallet, AccountBox, AccountCircle, AddShoppingCart,
    Alarm, AlarmAdd, AlarmOff, AlarmOn, AllInbox, AllOut, Android, Announcement, ArrowRightAlt, AspectRatio, Assessment, Assignment, AssignmentInd, AssignmentLate,
    AssignmentReturn, AssignmentReturned, AssignmentTurnedIn, Autorenew, Backup, Book, Bookmark, BookmarkBorder, Bookmarks, BugReport, Build, Cached, CalendarToday,
    Delete, Home, Search,
    //CalendarViewDay, CameraEnhance, CardGiftcard, CardMembership, CardTravel, ChangeHistory, CheckCircle, CheckCircleOutline, ChromeReaderMode, Class, Code, Commute,
    //CompareArrows, ContactSupport, Copyright, CreditCard, Dashboard, DateRange, Delete, DeleteForever, DeleteOutline, Description, Dns, Done, DoneAll, DoneOutline,
    //DonutLarge, DonutSmall, DragIndicator, Eject, EuroSymbol, Event, EventSeat, ExitToApp, Explore, ExploreOff, Extension, Face, Favorite, FavoriteBorder, Feedback,
    //FindInPage, FindReplace, Fingerprint, FlightLand, FlightTakeoff, FlipToBack, FlipToFront, GTranslate, Gavel, GetApp, Gif, Grade, GroupWork, Help, HelpOutline,
    //HighlightOff, History, Home, HorizontalSplit, HourglassEmpty, HourglassFull, Http, Https, ImportantDevices, Info, Input, InvertColors, Label, LabelImportant,
    //LabelOff, Language, Launch, LineStyle, LineWeight, List, Lock, LockOpen, Loyalty, MarkunreadMailbox, Maximize, Minimize, Motorcycle, NoteAdd, OfflineBolt, OfflinePin,
    //Opacity, OpenInBrowser, OpenInNew, OpenWith, Pageview, PanTool, Payment, PermCameraMic, PermContactCalendar, PermDataSetting, PermDeviceInformation, PermIdentity,
    //PermMedia, PermPhoneMsg, PermScanWifi, pets, PictureInPicture, PictureInPictureAlt, PlayForWork, Polymer, PowerSettingsNew, PregnantWoman, Print, QueryBuilder,
    //QuestionAnswer, Receipt, RecordVoiceOver, Redeem, RemoveShoppingCart, Reorder, ReportProblem, Restore, RestoreFromTrash, RestorePage, Room, RoundedCorner, Rowing,
    //Schedule, Search, Settings, SettingsApplications, SettingsBackupRestore, SettingsBluetooth, SettingsBrightness, SettingsCell, SettingsEthernet, SettingsInputAntenna,
    //SettingsInputComponent, SettingsInputComposite, SettingsInputSvideo, SettingsOverscan, SettingsPhone, SettingsPower, SettingsRemote, SettingsVoice, Shop, ShopTwo,
    //ShoppingBasket, ShoppingCart, SpeakerNotes, SpeakerNotesOff, Spellcheck, StarRate, Stars, Store, Subject, SupervisedUserCircle, SupervisorAccount, SwapHoriz,
    //SwapHorizontalCircle, SwapVert, SwapVerticalCircle, Tab, TabUnselected, TextRotateUp, TextRotateVertical, TextRotationDown, TextRotationNone, Theaters, ThumbDown,
    //ThumbUp, ThumbsUpDown, Timeline, Toc, Today, Toll, TouchApp, TrackChanges, Translate, TrendingDown, TrendingFlat, TrendingUp, TurnedIn, TurnedInNot, Update,
    //VerifiedUser, VerticalSplit, ViewAgenda, ViewArray, ViewCarousel, ViewColumn, ViewDay, ViewHeadline, ViewList, ViewModule, ViewQuilt, ViewStream, ViewWeek, Visibility,
    //VisibilityOff, VoiceOverOff, WatchLater, Work, WorkOff, WorkOutline, YoutubeSearchedFor, ZoomIn, ZoomOut
    ChangeHistory, CheckCircle, Code, Commute, CompareArrows, ContactSupport, Copyright, CreditCard, Dashboard, DateRange, Description, Done    
} from '@material-ui/icons';
// Alert icons
import {
    AddAlert, Error, ErrorOutline, NotificationImportant, Warning
} from '@material-ui/icons';
import {
    Add, CloudUpload, Drafts, Edit, Inbox, KeyboardVoice, Mail, Save, Send
} from '@material-ui/icons';

import MenuIcon from '@material-ui/icons/Menu';

// Communication icons
import{
    AlternateEmail, Business, Call, CallEnd, CallMade, CallMerge, CallMissed, CallMissedOutgoing, CallReceived, CallSplit, CancelPresentation, CellWifi, Chat, ChatBubble, ChatBubbleOutline, 
    ClearAll, Comment, ContactMail, ContactPhone, Contacts, DesktopAccessDisabled, DialerSip, Dialpad, DomainDisabled, Duo, Email, Forum, ImportContacts, ImportExport, InvertColors, ListAlt, LiveHelp,
    LocationOff, LocationOn, MailOutline, Message, MobileScreenShare, NoSim, PausePresentation, PersonAddDisabled, Phone, PhonelinkErase, PhonelinkLock, PhonelinkRing, PhonelinkSetup, PortableWifiOff,
    PresentToAll, PrintDisabled, RingVolume, RssFeed, ScreenShare, SentimentSatisfiedAlt, SpeakerPhone, StayCurrentLandscape, StayCurrentPortrait, StayPrimaryLandscape, StayPrimaryPortrait, StopScreenShare,
    SwapCalls, Textsms, Unsubscribe, Voicemail, VpnKey

} from '@material-ui/icons';

//Maps Icons
import{
   ThreeSixty, AddLocation, Atm, Beenhere, Category, CompassCalibration, DepartureBoard, Directions, DirectionsBike, DirectionsBoat, DirectionsBus, DirectionsCar, DirectionsRailway, DirectionsRun,
   DirectionsSubway, DirectionsTransit, DirectionsWalk, EditAttributes, EditLocation, EvStation, Fastfood, Flight, Hotel, Layers, LayersClear, LocalActivity, LocalAirport, LocalAtm, LocalBar, LocalCafe, LocalCarWash,
   LocalConvenienceStore, LocalDining, LocalDrink, LocalFlorist, LocalGasStation, LocalGroceryStore, LocalHospital, LocalHotel, LocalLaundryService, LocalLibrary, LocalMall, LocalMovies, LocalOffer, LocalParking,
   LocalPharmacy, LocalPhone, LocalPizza, LocalPlay, LocalPostOffice, LocalPrintshop, LocalSee, LocalShipping, LocalTaxi, Map, Money, MyLocation, Navigation, NearMe, NotListedLocation, PersonPin, PersonPinCircle,
   PinDrop, Place, RateReview, Restaurant, RestaurantMenu, Satellite, StoreMallDirectory, Streetview, Subway, Terrain, Traffic, Train, Tram, TransferWithinAStation, TransitEnterexit, TripOrigin, ZoomOutMap
} from '@material-ui/icons';

// Navigation icons
import{
   Apps, ArrowBack, ArrowBackIos, ArrowDownward, ArrowDropDown, ArrowDropDownCircle, ArrowDropUp, ArrowForward, ArrowForwardIos, ArrowLeft, ArrowRight, ArrowUpward, Cancel, Check, ChevronLeft, ChevronRight, 
   Close, ExpandLess, ExpandMore, FirstPage, Fullscreen, FullscreenExit, LastPage, MoreHoriz, MoreVert, Refresh, SubdirectoryArrowLeft, SubdirectoryArrowRight, UnfoldLess, UnfoldMore
} from '@material-ui/icons';

// Social icons
import{
    Cake, Domain, Group, GroupAdd, LocationCity, Mood, MoodBad, Notifications, NotificationsActive, NotificationsNone, NotificationsOff, NotificationsPaused, Pages, PartyMode, People, PeopleOutline, Person, 
    PersonAdd, PersonOutline, PlusOne, Poll, Public, School, SentimentDissatisfied, SentimentSatisfied, SentimentVeryDissatisfied, SentimentVerySatisfied, Share, ThumbDownAlt, ThumbUpAlt, Whatshot
 } from '@material-ui/icons';

import { ContentCut, ContentCopy, ContentPaste, ContentSave, Pencil, Redo } from 'muicons/dist';

// 3rd party
import ReactMarkdown from 'react-markdown';
import DataTable from 'mui-datatables';

export const componentMap = {
    'AppBar': AppBar,
    'Avatar': Avatar,
    'Backdrop': Backdrop,
    'Badge': Badge,
    'BottomNavigation': BottomNavigation,
    'BottomNavigationAction': BottomNavigationAction,
    'Button': Button,
    'ButtonBase': ButtonBase,
    'Card': Card,
    'CardActionArea': CardActionArea,
    'CardActions': CardActions,
    'CardContent': CardContent,
    'CardHeader': CardHeader,
    'CardMedia': CardMedia,
    'Chip': Chip,
    'Checkbox': Checkbox,
    'CircularProgress': CircularProgress,
    'ClickAwayListener': ClickAwayListener,
    'Collapse': Collapse,
    'Dialog': Dialog,
    'DialogActions': DialogActions,
    'DialogContent': DialogContent,
    'DialogContentText': DialogContentText,
    'DialogTitle': DialogTitle,
    'Divider': Divider,
    'Drawer': Drawer,
    'ExpansionPanel': ExpansionPanel,
    'ExpansionPanelActions': ExpansionPanelActions,
    'ExpansionPanelDetails': ExpansionPanelDetails,
    'ExpansionPanelSummary': ExpansionPanelSummary,
    'Fab': Fab,
    'Fade': Fade,
    'FilledInput': FilledInput,
    'FormControl': FormControl,
    'FormControlLabel': FormControlLabel,
    'FormGroup': FormGroup,
    'FormHelperText': FormHelperText,
    'FormLabel': FormLabel,
    'Grid': Grid,
    'GridList': GridList,
    'GridListTile': GridListTile,
    'GridListTileBar': GridListTileBar,
    'Grow': Grow,
    'Hidden': Hidden,
    'Icon': Icon,
    'IconButton': IconButton,
    'Input': Input,
    'InputAdornment': InputAdornment,
    'InputBase': InputBase,
    'InputLabel': InputLabel,
    'LinearProgress': LinearProgress,
    'Link': Link,
    'List': List,
    'ListItem': ListItem,
    'ListItemAvatar': ListItemAvatar,
    'ListItemIcon': ListItemIcon,
    'ListItemSecondaryAction': ListItemSecondaryAction,
    'ListItemText': ListItemText,
    'ListSubheader': ListSubheader,
    'Menu': Menu,
    'MenuItem': MenuItem,
    'MenuList': MenuList,
    'MobileStepper': MobileStepper,
    'Modal': Modal,
    'MuiThemeProvider': MuiThemeProvider,
    'NativeSelect': NativeSelect,
    'OutlinedInput': OutlinedInput,
    'Paper': Paper,
    'Popover': Popover,
    'Popper': Popper,
    'Portal': Portal,
    'Radio': Radio,
    'RadioGroup': RadioGroup,
    'Select': Select,
    'Slide': Slide,
    'Snackbar': Snackbar,
    'SnackbarContent': SnackbarContent,
    'Step': Step,
    'StepButton': StepButton,
    'StepConnector': StepConnector,
    'StepContent': StepContent,
    'StepIcon': StepIcon,
    'StepLabel': StepLabel,
    'Stepper': Stepper,
    'SvgIcon': SvgIcon,
    'SwipeableDrawer': SwipeableDrawer,
    'Switch': Switch,
    'Tab': Tab,
    'Table': Table,
    'TableBody': TableBody,
    'TableCell': TableCell,
    'TableFooter': TableFooter,
    'TableHead': TableHead,
    'TablePagination': TablePagination,
    'TableRow': TableRow,
    'TableSortLabel': TableSortLabel,
    'Tabs': Tabs,
    'TextField': TextField,
    'Toolbar': Toolbar,
    'Tooltip': Tooltip,
    'TouchRipple': TouchRipple,
    'Typography': Typography,
    'Zoom': Zoom,

    // 3rd Party
    'Markdown': ReactMarkdown,
    'DataTable': DataTable,

    // Material icons - Action
    'ThreeDRotation': ThreeDRotation,
    'Accessibility': Accessibility,
    'AccessibilityNew': AccessibilityNew,
    'Accessible': Accessible,
    'AccessibleForward': AccessibleForward,
    'AccountBalance': AccountBalance,
    'AccountBalanceWallet': AccountBalanceWallet,
    'AccountBox': AccountBox,
    'AccountCircle': AccountCircle,
    'AddShoppingCart': AddShoppingCart,
    'Alarm': Alarm,
    'AlarmAdd': AlarmAdd,
    'AlarmOff': AlarmOff,
    'AlarmOn': AlarmOn,
    'AllInbox': AllInbox,
    'AllOut': AllOut,
    'Android': Android,
    'Announcement': Announcement,
    'ArrowRightAlt': ArrowRightAlt,
    'AspectRatio': AspectRatio,
    'Assessment': Assessment,
    'Assignment': Assignment,
    'AssignmentInd': AssignmentInd,
    'AssignmentLate': AssignmentLate,
    'AssignmentReturn': AssignmentReturn,
    'AssignmentReturned': AssignmentReturned,
    'AssignmentTurnedIn': AssignmentTurnedIn,
    'Autorenew': Autorenew,
    'Backup': Backup,
    'Book': Book,
    'Bookmark': Bookmark,
    'BookmarkBorder': BookmarkBorder,
    'Bookmarks': Bookmarks,
    'BugReport': BugReport,
    'Build': Build,
    'Cached': Cached,
    'CalendarToday': CalendarToday,
    'Delete': Delete,
    'Home': Home,
    'Search': Search,

    // Material icons - Alert
    'AddAlert': AddAlert,
    'Error': Error,
    'ErrorOutline': ErrorOutline,
    'NotificationImportant': NotificationImportant,
    'Warning': Warning,

    // Material icons - Other
    'Add': Add,
    'ChangeHistory': ChangeHistory,
    'CheckCircle': CheckCircle,
    'Code': Code,
    'Commute': Commute,
    'CompareArrows': CompareArrows,
    'ContactSupport':ContactSupport,
    'Copyright':Copyright,
    'CreditCard': CreditCard,
    'Dashboard': Dashboard,
    'DateRange': DateRange,
    'Description': Description,
    'Done': Done,
    'CloudUpload': CloudUpload,
    'Drafts': Drafts,
    'Edit': Edit,
    'Inbox': Inbox,
    'KeyboardVoice': KeyboardVoice,
    'Mail': Mail,
    'MenuIcon': MenuIcon,
    'Save': Save,
    'Send': Send,

    // MUI icons
    'ContentCut': ContentCut,
    'ContentCopy': ContentCopy,
    'ContentPaste': ContentPaste,
    'ContentSave': ContentSave,
    'Pencil': Pencil,
    'Redo': Redo,

    //Communication icons
    'AlternateEmail': AlternateEmail, 
    'Business': Business, 
    'Call': Call, 
    'CallEnd': CallEnd, 
    'CallMade': CallMade, 
    'CallMerge': CallMerge, 
    'CallMissed': CallMissed, 
    'CallMissedOutgoing': CallMissedOutgoing, 
    'CallReceived': CallReceived, 
    'CallSplit': CallSplit, 
    'CancelPresentation': CancelPresentation, 
    'CellWifi': CellWifi, 
    'Chat': Chat, 
    'ChatBubble': ChatBubble, 
    'ChatBubbleOutline': ChatBubbleOutline, 
    'ClearAll': ClearAll, 
    'Comment': Comment, 
    'ContactMail': ContactMail, 
    'ContactPhone': ContactPhone, 
    'Contacts': Contacts, 
    'DesktopAccessDisabled': DesktopAccessDisabled, 
    'DialerSip': DialerSip, 
    'Dialpad': Dialpad, 
    'DomainDisabled': DomainDisabled, 
    'Duo': Duo, 
    'Email': Email, 
    'Forum': Forum, 
    'ImportContacts': ImportContacts, 
    'ImportExport': ImportExport, 
    'InvertColors': InvertColors, 
    'ListAlt': ListAlt, 
    'LiveHelp': LiveHelp,
    'LocationOff': LocationOff, 
    'LocationOn': LocationOn, 
    'MailOutline': MailOutline, 
    'Message': Message, 
    'MobileScreenShare': MobileScreenShare, 
    'NoSim': NoSim, 
    'PausePresentation': PausePresentation, 
    'PersonAddDisabled': PersonAddDisabled, 
    'Phone': Phone, 
    'PhonelinkErase': PhonelinkErase, 
    'PhonelinkLock': PhonelinkLock, 
    'PhonelinkRing': PhonelinkRing, 
    'PhonelinkSetup': PhonelinkSetup, 
    'PortableWifiOff': PortableWifiOff,
    'PresentToAll': PresentToAll, 
    'PrintDisabled': PrintDisabled, 
    'RingVolume': RingVolume, 
    'RssFeed': RssFeed, 
    'ScreenShare': ScreenShare, 
    'SentimentSatisfiedAlt': SentimentSatisfiedAlt, 
    'SpeakerPhone': SpeakerPhone, 
    'StayCurrentLandscape': StayCurrentLandscape, 
    'StayCurrentPortrait': StayCurrentPortrait, 
    'StayPrimaryLandscape': StayPrimaryLandscape, 
    'StayPrimaryPortrait': StayPrimaryPortrait, 
    'StopScreenShare': StopScreenShare,
    'SwapCalls': SwapCalls, 
    'Textsms': Textsms, 
    'Unsubscribe': Unsubscribe, 
    'Voicemail': Voicemail, 
    'VpnKey': VpnKey,

    //Maps Icons
    'ThreeSixty': ThreeSixty, 
    'AddLocation': AddLocation, 
    'Atm': Atm, 
    'Beenhere': Beenhere, 
    'Category': Category, 
    'CompassCalibration': CompassCalibration, 
    'DepartureBoard': DepartureBoard, 
    'Directions': Directions, 
    'DirectionsBike': DirectionsBike, 
    'DirectionsBoat': DirectionsBoat, 
    'DirectionsBus': DirectionsBus, 
    'DirectionsCar': DirectionsCar, 
    'DirectionsRailway': DirectionsRailway, 
    'DirectionsRun': DirectionsRun,
    'DirectionsSubway': DirectionsSubway, 
    'DirectionsTransit': DirectionsTransit, 
    'DirectionsWalk': DirectionsWalk, 
    'EditAttributes': EditAttributes, 
    'EditLocation': EditLocation, 
    'EvStation': EvStation, 
    'Fastfood': Fastfood, 
    'Flight': Flight, 
    'Hotel': Hotel, 
    'Layers': Layers, 
    'LayersClear': LayersClear, 
    'LocalActivity': LocalActivity, 
    'LocalAirport': LocalAirport, 
    'LocalAtm': LocalAtm, 
    'LocalBar': LocalBar, 
    'LocalCafe': LocalCafe, 
    'LocalCarWash': LocalCarWash,
    'LocalConvenienceStore': LocalConvenienceStore, 
    'LocalDining': LocalDining, 
    'LocalDrink': LocalDrink, 
    'LocalFlorist': LocalFlorist, 
    'LocalGasStation': LocalGasStation, 
    'LocalGroceryStore': LocalGroceryStore, 
    'LocalHospital': LocalHospital, 
    'LocalHotel': LocalHotel, 
    'LocalLaundryService': LocalLaundryService, 
    'LocalLibrary': LocalLibrary, 
    'LocalMall': LocalMall, 
    'LocalMovies': LocalMovies, 
    'LocalOffer': LocalOffer, 
    'LocalParking': LocalParking,
    'LocalPharmacy': LocalPharmacy, 
    'LocalPhone': LocalPhone, 
    'LocalPizza': LocalPizza, 
    'LocalPlay': LocalPlay, 
    'LocalPostOffice': LocalPostOffice, 
    'LocalPrintshop': LocalPrintshop, 
    'LocalSee': LocalSee, 
    'LocalShipping': LocalShipping, 
    'LocalTaxi': LocalTaxi, 
    'Map': Map, 
    'Money': Money, 
    'MyLocation': MyLocation, 
    'Navigation': Navigation, 
    'NearMe': NearMe, 
    'NotListedLocation': NotListedLocation, 
    'PersonPin': PersonPin, 
    'PersonPinCircle': PersonPinCircle,
    'PinDrop': PinDrop, 
    'Place': Place, 
    'RateReview': RateReview, 
    'Restaurant': Restaurant, 
    'RestaurantMenu': RestaurantMenu, 
    'Satellite': Satellite, 
    'StoreMallDirectory': StoreMallDirectory, 
    'Streetview': Streetview, 
    'Subway': Subway, 
    'Terrain': Terrain, 
    'Traffic': Traffic, 
    'Train': Train, 
    'Tram': Tram, 
    'TransferWithinAStation': TransferWithinAStation, 
    'TransitEnterexit': TransitEnterexit, 
    'TripOrigin': TripOrigin, 
    'ZoomOutMap': ZoomOutMap,

    //Navigation Icons
    'Apps': Apps, 
    'ArrowBack': ArrowBack, 
    'ArrowBackIos': ArrowBackIos, 
    'ArrowDownward': ArrowDownward, 
    'ArrowDropDown': ArrowDropDown, 
    'ArrowDropDownCircle': ArrowDropDownCircle, 
    'ArrowDropUp': ArrowDropUp, 
    'ArrowForward': ArrowForward, 
    'ArrowForwardIos': ArrowForwardIos, 
    'ArrowLeft': ArrowLeft, 
    'ArrowRight': ArrowRight, 
    'ArrowUpward': ArrowUpward, 
    'Cancel': Cancel, 
    'Check': Check, 
    'ChevronLeft': ChevronLeft, 
    'ChevronRight': ChevronRight, 
    'Close': Close, 
    'ExpandLess': ExpandLess, 
    'ExpandMore': ExpandMore, 
    'FirstPage': FirstPage, 
    'Fullscreen': Fullscreen, 
    'FullscreenExit': FullscreenExit, 
    'LastPage': LastPage, 
    'MoreHoriz': MoreHoriz, 
    'MoreVert': MoreVert, 
    'Refresh': Refresh, 
    'SubdirectoryArrowLeft': SubdirectoryArrowLeft, 
    'SubdirectoryArrowRight': SubdirectoryArrowRight, 
    'UnfoldLess': UnfoldLess, 
    'UnfoldMore': UnfoldMore,

     //Social Icons
     'Cake': Cake, 
     'Domain': Domain, 
     'Group' : Group, 
     'GroupAdd': GroupAdd, 
     'LocationCity': LocationCity,
     'Mood': Mood, 
     'MoodBad': MoodBad, 
     'Notifications': Notifications, 
     'NotificationsActive': NotificationsActive, 
     'NotificationsNone': NotificationsNone, 
     'NotificationsOff': NotificationsOff, 
     'NotificationsPaused': NotificationsPaused, 
     'Pages': Pages, 
     'PartyMode': PartyMode, 
     'People': People, 
     'PeopleOutline': PeopleOutline, 
     'Person': Person, 
     'PersonAdd': PersonAdd, 
     'PersonOutline': PersonOutline, 
     'PlusOne': PlusOne, 
     'Poll': Poll, 
     'Public': Public, 
     'School': School, 
     'SentimentDissatisfied': SentimentDissatisfied, 
     'SentimentSatisfied': SentimentSatisfied, 
     'SentimentVeryDissatisfied': SentimentVeryDissatisfied, 
     'SentimentVerySatisfied': SentimentVerySatisfied, 
     'Share': Share, 
     'ThumbDownAlt': ThumbDownAlt, 
     'ThumbUpAlt': ThumbUpAlt, 
     'Whatshot': Whatshot
};