import {
    AppBar, Avatar, Backdrop, Badge, BottomNavigation, BottomNavigationAction, Button, ButtonBase, Card, CardActionArea, CardActions, CardContent, CardHeader,
    CardMedia, Checkbox, Chip, CircularProgress, ClickAwayListener, Collapse, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Divider,
    Drawer, ExpansionPanel, ExpansionPanelActions, ExpansionPanelDetails, ExpansionPanelSummary, Fab, Fade, FilledInput, FormControl, FormControlLabel,
    FormGroup, FormHelperText, FormLabel, Grid, GridList, GridListTile, GridListTileBar, Grow, Hidden, Icon, IconButton, Input, InputAdornment, InputBase,
    InputLabel, LinearProgress, Link, List, ListItem, ListItemAvatar, ListItemIcon, ListItemSecondaryAction, ListItemText, ListSubheader, Menu, MenuItem,
    MenuList, MobileStepper, Modal, MuiThemeProvider, NativeSelect, OutlinedInput, Paper, Popover, Popper, Portal, Radio, RadioGroup, Select, Slide, Snackbar,
    SnackbarContent, Step, StepButton, StepConnector, StepContent, StepIcon, StepLabel, Stepper, SvgIcon, SwipeableDrawer, Switch, Tab, Table, TableBody, TableCell,
    TableFooter, TableHead, TablePagination, TableRow, TableSortLabel, Tabs, TextField, Toolbar, Tooltip, Typography, Zoom
} from '@material-ui/core';
import TouchRipple from '@material-ui/core/ButtonBase/TouchRipple';

// 3rd party
import ReactMarkdown from 'react-markdown';
import DataTable from 'mui-datatables';

export const componentMap = {
    'AppBar': AppBar,
    'Avatar': Avatar,
    'Backdrop': Backdrop,
    'Badge': Badge,
    'BottomNavigation': BottomNavigation,
    'BottomNavigationAction': BottomNavigationAction,
    'Button': Button,
    'ButtonBase': ButtonBase,
    'Card': Card,
    'CardActionArea': CardActionArea,
    'CardActions': CardActions,
    'CardContent': CardContent,
    'CardHeader': CardHeader,
    'CardMedia': CardMedia,
    'Chip': Chip,
    'Checkbox': Checkbox,
    'CircularProgress': CircularProgress,
    'ClickAwayListener': ClickAwayListener,
    'Collapse': Collapse,
    'Dialog': Dialog,
    'DialogActions': DialogActions,
    'DialogContent': DialogContent,
    'DialogContentText': DialogContentText,
    'DialogTitle': DialogTitle,
    'Divider': Divider,
    'Drawer': Drawer,
    'ExpansionPanel': ExpansionPanel,
    'ExpansionPanelActions': ExpansionPanelActions,
    'ExpansionPanelDetails': ExpansionPanelDetails,
    'ExpansionPanelSummary': ExpansionPanelSummary,
    'Fab': Fab,
    'Fade': Fade,
    'FilledInput': FilledInput,
    'FormControl': FormControl,
    'FormControlLabel': FormControlLabel,
    'FormGroup': FormGroup,
    'FormHelperText': FormHelperText,
    'FormLabel': FormLabel,
    'Grid': Grid,
    'GridList': GridList,
    'GridListTile': GridListTile,
    'GridListTileBar': GridListTileBar,
    'Grow': Grow,
    'Hidden': Hidden,
    'Icon': Icon,
    'IconButton': IconButton,
    'Input': Input,
    'InputAdornment': InputAdornment,
    'InputBase': InputBase,
    'InputLabel': InputLabel,
    'LinearProgress': LinearProgress,
    'Link': Link,
    'List': List,
    'ListItem': ListItem,
    'ListItemAvatar': ListItemAvatar,
    'ListItemIcon': ListItemIcon,
    'ListItemSecondaryAction': ListItemSecondaryAction,
    'ListItemText': ListItemText,
    'ListSubheader': ListSubheader,
    'Menu': Menu,
    'MenuItem': MenuItem,
    'MenuList': MenuList,
    'MobileStepper': MobileStepper,
    'Modal': Modal,
    'MuiThemeProvider': MuiThemeProvider,
    'NativeSelect': NativeSelect,
    'OutlinedInput': OutlinedInput,
    'Paper': Paper,
    'Popover': Popover,
    'Popper': Popper,
    'Portal': Portal,
    'Radio': Radio,
    'RadioGroup': RadioGroup,
    'Select': Select,
    'Slide': Slide,
    'Snackbar': Snackbar,
    'SnackbarContent': SnackbarContent,
    'Step': Step,
    'StepButton': StepButton,
    'StepConnector': StepConnector,
    'StepContent': StepContent,
    'StepIcon': StepIcon,
    'StepLabel': StepLabel,
    'Stepper': Stepper,
    'SvgIcon': SvgIcon,
    'SwipeableDrawer': SwipeableDrawer,
    'Switch': Switch,
    'Tab': Tab,
    'Table': Table,
    'TableBody': TableBody,
    'TableCell': TableCell,
    'TableFooter': TableFooter,
    'TableHead': TableHead,
    'TablePagination': TablePagination,
    'TableRow': TableRow,
    'TableSortLabel': TableSortLabel,
    'Tabs': Tabs,
    'TextField': TextField,
    'Toolbar': Toolbar,
    'Tooltip': Tooltip,
    'TouchRipple': TouchRipple,
    'Typography': Typography,
    'Zoom': Zoom,

    // 3rd Party
    'Markdown': ReactMarkdown,
    'DataTable': DataTable
};