import React, { Component } from 'react';

class InfoPage extends Component {
    render() {
        return (
        <div>
            <h1>Generated by Material UI Designer.</h1>
        </div>
        );
    }
}

export default InfoPage;